baseURL = 'https://www.rahulkande.com/'
languageCode = 'en-us'
title = 'Rahul Kande'
theme = "hugo-coder"
defaultcontentlanguage = "en-us"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
  author = "Rahul Kande"
  # license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
  info = ["Ph.D. Student", "Secure and Trustworthy Hardware (SETH) Lab", "Texas A&M University"]
  description = "Rahul Kande's website"
  keywords = "rahul,kande,TAMU,rahulkande,TheHuzz,SETH,security,hardware,vulnerabilities,RISC-V,Hack@EVENT"
  avatarurl = "images/rahul.jpg"
  
  favicon_32 = "images/male32.png"
  favicon_16 = "images/male16.png"
  
  
  dateFormat = "September 2, 2022" 
  since = 2022

  enableTwemoji = true

  colorScheme = "auto"  # dark, light, auto
  hidecolorschemetoggle = false
  
  #customCSS = ["css/custom.css"]
  #customSCSS = ["scss/custom.scss"]
  #customJS = ["js/custom.js"]
  
  
  # Git Commit in Footer, uncomment the line below to enable it
  # commit = "https://github.com/luizdepra/hugo-coder/tree/"
  
  # Right To Left, shift content direction for languagues such as Arabic
  rtl = false
  
  # Series see also post count
  maxSeeAlsoItems = 5
  
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/rahulkande"
  
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/rahulkande"
  
  
	[[params.social]]
	name = "LinkedIn"
	icon = "fa fa-2x fa-linkedin"
	weight = 4
	url = "https://www.linkedin.com/in/rahulkande/"

# Menu links
[[menu.main]]
  name = "Publications"
  weight = 1
  url  = "publications/"
[[menu.main]]
  name = "Contact me"
  weight = 2
  url = "contact/"