baseURL: https://www.rahulkande.com/
languageCode: en-us
title: Rahul Kande
theme: 
- hugo-coder
#- PaperMod
#- hugo-piko

defaultcontentlanguage: en-us

paginate: 20

pygmentsstyle: bw
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
enableEmoji: true
# Enable Disqus comments
# disqusShortname: yourdiscussshortname

params:
  author: Rahul Kande
  # license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
  info: ["Ph.D. Student in Computer Engineering", "Secure and Trustworthy Hardware (SETH) Lab", "Texas A&M University"]
  description: Rahul Kande's website
  keywords: "rahul,kande,TAMU,rahulkande,TheHuzz,SETH,security,hardware,vulnerabilities,RISC-V,Hack@EVENT"
  avatarurl: images/rahul.jpg
  
  favicon_32: images/male32.png
  favicon_16: images/male16.png
  
  
  #dateFormat: September 2, 2006
  since: 2022

  enableTwemoji: true

  colorScheme: auto # dark, light, auto
  hidecolorschemetoggle: false
  
  #customCSS: ["css/custom.css"]
  #customSCSS: ["scss/custom.scss"]
  #customJS: ["js/custom.js"]
  
  
  # Git Commit in Footer, uncomment the line below to enable it
  # commit: "https://github.com/luizdepra/hugo-coder/tree/"
  
  # Right To Left, shift content direction for languagues such as Arabic
  rtl: false
  
  # Series see also post count
  maxSeeAlsoItems: 5
 
  # social links
  social:
    - name: Github
      icon: fa fa-github fa-2x
      weight: 60
      url: https://github.com/rahulkande
    - name: Gitlab
      icon: fa fa-gitlab fa-2x
      weight: 50
      url: https://gitlab.com/rahulkande
    - name: "LinkedIn"
      icon: fa fa-2x fa-linkedin
      weight: 20
      url: https://www.linkedin.com/in/rahulkande/
    - name: "Email"
      icon: fa fa-2x fa-envelope
      weight: 1
      url: mailto:rahulkande@tamu.edu
    - name: "Google Scholar"
      icon: ai ai-google-scholar ai-2x
      weight: 10
      url: https://scholar.google.com/citations?user=4X6V5rwAAAAJ&hl=en&oi=ao
 

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

# Menu links
menu:
  main:
  - identifier: publications
    name: Publications
    weight: 1
    url: "/publications/"

  # - identifier: "test"
  #   name: "Test"
  #   weight: 2
  #   url: "/test/"

  # - identifier: "contact us"
  #   name: "Contact me"
  #   weight: 2
  #   url: "/contact/"